---
name: Main workflow

on:
  push:

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
  tag-release:
    if: github.ref == 'refs/heads/main'
    needs: test
    uses: ./.github/workflows/tag.yml
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
